remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: [Textual Element Impact on Predicting Recipe Ratings]
description: [This site serves as a easily accessible report on our findings regarding the relationship of textual element on recipie ratings.]
